server: 
  port: 3344 
  
spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gcr128/microservicecloud-config.git #GitHub上面的git仓库名字
          #username: gcr1208@163.com
          #password: gcr6631795
          #default-label: master
          #force-pull: true
          # https://github.com/gcr128/microservicecloud-config.git
          # git@github.com:gcr128/microservicecloud-config.git

 

